[server]
port = "80"

[[api]]
method = "get"
url = "/get/user.json"

[[api]]
method = "post"
url = "/post/user.json"

[[api]]
method = "get"
url = "/get/address.json"

[[api]]
method = "get"
url = "/get/address.xml"

